import { readFileSync, writeFileSync } from 'fs'

const DETAILS = {
  'ls -lah': 'list的缩写，列出目录内容。-l长格式显示权限/所有者/大小/时间，-a显示隐藏文件(以.开头)，-h人类可读大小(KB/MB)。最基础最常用的命令，几乎每次操作目录都会用到。配合-t按时间排序、-S按大小排序、-r逆序使用更灵活。',
  'cd': 'change directory切换工作目录。参数可为绝对路径(/开头)或相对路径。特殊值：.当前目录、..上级目录、~用户家目录、-上一次目录。cd不带参数默认回~。路径含空格需用引号或转义。是shell内建命令，不产生新进程。',
  'grep -rn': 'global regex print，在文件内容中搜索匹配的行。-r递归搜索子目录，-n显示行号，-i忽略大小写，-v反向匹配(显示不包含的行)，-l只显示文件名，-c只显示匹配数。支持正则：^行首、$行尾、.任意字符、*重复。日志排查、代码搜索的核心工具，常配合管道使用。',
  'find': '在目录树中按条件查找文件。-name按文件名(支持通配符*)，-type f/d按类型，-mtime -7修改时间7天内，-size +100M大于100M，-exec对结果执行命令。注意：find会真实遍历磁盘，大目录较慢；查找当前目录用.。常与xargs、-delete、-exec配合实现批量操作。',
  'chmod / chown': 'chmod修改文件权限(rwx读/写/执行)，数字模式755=所有者rwx+组r-x+其他r-x，字母模式u+x给所有者加执行权限。chown修改所有者:组。权限对脚本执行、Web服务器访问控制至关重要。递归修改用-R。注意：误改系统文件权限可能导致服务无法运行。',
  'tar': 'tape archive磁带归档，打包/解压工具。-c创建、-x解压、-z用gzip压缩(.tar.gz)、-j用bzip2(.tar.bz2)、-v显示过程、-f指定文件名。注意：-f后必须紧跟文件名。打包时排除文件用--exclude。是Linux下最常用的压缩格式，跨平台传输首选。',
  'ps aux': 'process status查看进程。a显示所有用户进程，u以用户为主格式，x显示无控制终端的进程。输出列：USER/PID/%CPU/%MEM/VSZ/RSS/TTY/STAT/START/TIME/COMMAND。STAT中R运行/S睡眠/Z僵尸/D不可中断。配合grep查找特定进程，是进程排查第一步。',
  'kill / killall': '向进程发送信号。kill需指定PID，killall按进程名。-9(SIGKILL)强制终止(不可捕获，可能丢数据)，-15(SIGTERM)优雅终止(默认，允许清理)，-1(SIGHUP)重载配置，-2(SIGINT)相当于Ctrl+C。注意：优先用-15让进程优雅退出，-9是最后手段。kill -l查看所有信号。',
  'netstat / ss': '查看网络连接/端口/路由表。ss是netstat的现代替代品(更快，默认已装)。-t TCP、-u UDP、-l监听端口、-n不解析名字(快)、-p显示进程。排查端口占用、连接状态、网络问题的首选。TIME_WAIT过多、端口冲突等问题的排查利器。注意：-p需要root权限。',
  'curl': 'transfer URL，命令行HTTP客户端。支持GET/POST/PUT/DELETE等，-X指定方法，-H加请求头，-d发数据，-o保存到文件，-I只取响应头，-L跟随重定向，-k忽略SSL证书，-s静默。还可测FTP/SMTP/TELNET等协议。API调试、下载文件、健康检查、性能测试的万能工具。',
  'wget': 'web get，非交互式下载工具。-c断点续传、-r递归下载整站、-m镜像网站、-O指定输出文件名、-q静默、-t 0无限重试、--limit-rate限速。比curl更适合大文件下载和整站抓取。注意：-r递归下载会创建大量文件，谨慎使用；下载脚本时配合--no-check-certificate跳过HTTPS验证。',
  'top / htop': '实时监控系统资源。top是系统自带，按CPU/内存排序进程，交互命令：P按CPU排序、M按内存、k杀进程、q退出、1显示各CPU核心。htop是增强版(需安装)，彩色显示、支持鼠标、更直观。默认3秒刷新，-d 1改为1秒。排查CPU/内存飙高的第一工具，按q退出。',
  'df -h': 'disk free查看文件系统磁盘使用情况。-h人类可读(KB/MB/GB)、-T显示文件系统类型、-i显示inode使用。输出列：Filesystem/Size/Used/Avail/Use%/Mounted on。当Use%超过90%需警惕。注意：df读的是文件系统级别，与du(目录级别)不同；网络挂载可能卡住，加-t ext4/xfs过滤本地磁盘。',
  'systemctl': '管理系统服务(systemd)。start/stop/restart启动停止重启，enable/disable开机自启，status查看状态，reload重载配置，is-active检查是否运行。systemd是现代Linux(init)的服务管理器，配置文件在/usr/lib/systemd/system/。注意：修改service文件后需daemon-reload；enable --now同时启用并启动。',
  'journalctl': '查看systemd日志(集中式二进制日志)。-u指定服务、-f实时跟踪(类似tail -f)、--since today/\"1 hour ago\"时间过滤、-p err按优先级、--no-pager不分页、-o json JSON格式。比传统日志更强大，支持按服务/时间/优先级过滤。注意：日志默认存/tmp可能重启丢失，配置/etc/systemd/journald.conf持久化。',
  'ssh': 'secure shell，加密远程登录。格式：ssh user@host -p端口。公钥认证：ssh-keygen生成密钥对，ssh-copy-id推送公钥，~/.ssh/config配置别名免输IP。端口转发-L本地/-R远程/-D动态。是远程服务器管理的基石，所有运维操作都基于SSH。注意：禁用root登录和密码登录(只用密钥)提升安全。',
  'scp / rsync': '基于SSH的文件传输。scp简单复制：scp local user@host:/path，-r递归。rsync增量同步：-a归档模式(保留权限/时间)、-v详细、-z压缩、--delete删除目标多余文件、--exclude排除、--progress进度。rsync只传差异部分，大文件/频繁同步远优于scp。注意：rsync --delete会删目标文件，谨慎使用。',
  'awk / sed': '文本处理三剑客之二。awk按列处理：$1第一列、NR行号、NF列数，支持BEGIN/END块和条件。sed流编辑器：s/old/new/g替换、d删除行、-i直接改文件。常配合管道做数据提取/转换。例如：ps aux|awk \'{sum+=$3}END{print sum}\'算总CPU。是Shell脚本中数据处理的核心工具，功能强大但语法需练习。',
  'crontab': '定时任务调度。crontab -e编辑、-l列出、-r删除。格式：分 时 日 月 周 命令，*任意值，*/5每5分钟，1-5周一到周五。文件在/var/spool/cron/。注意：环境变量可能缺失，建议脚本中source profile；%需转义\\%；输出默认发邮件，建议重定向到日志；最小粒度1分钟，需秒级用while或systemd timer。',
  'docker': '容器引擎。run创建并启动、ps列容器、images列镜像、build构建、pull/push推拉镜像、stop/rm删除。容器是轻量级隔离环境，共享内核无需完整OS。Dockerfile定义镜像构建步骤。注意：容器临时数据随删除丢失，持久化用-v挂载卷；生产环境建议用compose或K8s编排，而非裸docker命令。',
  'git': '分布式版本控制系统。add暂存、commit提交、push推送、pull拉取、clone克隆、branch分支、merge合并、log历史、status状态、diff差异、reset回退。.git目录存所有历史。分支模型：feature分支开发→合并到main。注意：commit前务必检查diff；push前先pull避免冲突；.gitignore排除不需版本管理的文件。',
  'vim / nano': '终端文本编辑器。vim：模式化编辑，i插入、Esc回正常、:wq保存退出、:q!不保存退出、dd删行、yy复制行、p粘贴、/搜索、:%s/old/new/g全局替换。nano：简单直观，Ctrl+O保存、Ctrl+X退出。vim学习曲线陡但效率极高，nano适合快速编辑。注意：vim中:w !sudo tee %可绕过权限保存。',
  'ln -s': '创建软链接(符号链接)，类似Windows快捷方式。格式：ln -s 目标 链接名。软链接指向目标路径，删除链接不影响原文件，删除原文件则链接失效(悬空链接)。常用于：版本切换(python→python3)、多版本共存、配置文件统一管理。注意：必须用绝对路径创建链接，相对路径容易出问题。',
  'env / export': '环境变量管理。env显示所有环境变量，export设置变量(对当前shell及子进程有效)，unset删除。PATH决定命令查找路径，HOME用户家目录，LANG语言编码。注意：export只在当前会话有效，永久生效需写入~/.bashrc或~/.bash_profile；$VAR引用变量，${VAR:-default}提供默认值。',
  'nohup / &': '后台运行进程。&放命令末尾使其后台运行，nohup使进程忽略挂断信号(SSH断开不终止)。组合：nohup cmd >log 2>&1 &将标准输出和错误都重定向到日志并后台运行。jobs查看后台任务，fg/bg前后台切换。注意：nohup不自动重定向，需手动加>log；现代推荐用systemd或tmux管理长期进程。',
  'screen / tmux': '终端复用器，一个物理终端开多个会话。tmux new -s name创建、detach分离(Ctrl+b d)、attach -t name重连、ls列出会话。核心价值：SSH断开后进程继续运行，重连恢复现场。还支持分屏、复制粘贴、会话共享(多人协作)。注意：tmux比screen更现代强大，推荐优先使用；配置文件~/.tmux.conf可自定义快捷键。',
  'free -h': '查看内存使用情况。-h人类可读、-s 2每2秒刷新、-m以MB为单位。输出：total总量/used已用/free空闲/shared共享/buff/cache缓冲缓存/available可用。注意：Linux会把空闲内存用作磁盘缓存(buff/cache)，这不影响应用使用，available才是真正可用的。看到free很少但available充足是正常的。',
  'iostat / vmstat': '系统性能监控。iostat看磁盘I/O：-x详细、1每秒刷新，关注%util(使用率>80%瓶颈)、await(等待ms)、r/s w/s读写IOPS。vmstat看综合状态：r就绪进程、b阻塞进程、swpd swap使用、si/so swap换入换出(非0说明内存不足)、bi/bo块I/O。注意：需安装sysstat包；首次运行显示自启动以来平均值，第二次才是实时值。',
  'sar': 'system activity report，系统历史性能数据采集/分析。sar -u CPU、-r内存、-n DEV网络、-d磁盘、-q负载，-f指定历史文件。数据由sysstat cron定期采集存/var/log/sa/。可回溯查看历史时段性能，定位\"昨晚3点发生了什么\"。注意：默认可能未启用采集，需在/etc/sysconfig/sysstat中ENABLED=true；数据默认保留7天。',
  'lsof': 'list open files，列出打开的文件/网络连接。因Linux一切皆文件，lsof可查：-i:80端口80的进程、-p 1234进程打开的文件、+D /tmp目录下打开的文件、-u user用户打开的文件。排查\"端口被谁占用\"、\"文件被谁锁定无法删除\"、\"进程在读写什么\"的利器。注意：输出可能很长，配合grep过滤；需root权限才能看所有进程。',
  'strace / ltrace': '系统调用/库调用追踪。strace追踪内核系统调用(open/read/write/fork等)，ltrace追踪库函数调用(malloc/printf等)。-p PID附加进程、-e trace=network只看网络、-f跟踪子进程、-c统计调用次数。用于排查程序卡住/崩溃/行为异常的根本原因。注意：有性能开销(2-10倍减速)，生产环境慎用；输出量大，建议过滤或重定向到文件。',
  'tcpdump': '命令行抓包工具，捕获/分析网络数据包。-i指定网卡、port 80过滤端口、host 1.2.3.4过滤主机、-nn不解析名字、-c 100抓100个包、-w存pcap文件。配合Wireshark图形分析。排查网络连接/协议/延迟问题的终极工具。注意：需root；抓包量大影响性能，用过滤表达式限制范围；生产环境谨慎长时间抓包。',
  'nc (netcat)': '网络工具瑞士军刀。-z端口扫描(不发数据)、-v详细、-l监听端口、-e绑定程序。用途：测试端口连通性(nc -zv host 80)、端口扫描(nc -z host 20-80)、传文件(nc -l 9999 <file / nc host 9999 >file)、简单聊天。比telnet更灵活，支持UDP。注意：-e有安全风险，某些发行版默认禁用；测试连通性比telnet快。',
  'ip / ifconfig': '网络接口配置。ip是ifconfig的现代替代(推荐)：ip addr查看/添加IP、ip route路由、ip link网卡up/down、ip neigh ARP表。ifconfig逐渐废弃但仍常见。注意：ip命令修改即时生效但重启丢失，永久配置需写网卡配置文件(/etc/sysconfig/network-scripts/或netplan)；ip addr show比ifconfig信息更全。',
  'firewalld / iptables': '防火墙管理。firewalld(CentOS7+)：--add-port=80/tcp添加端口、--permanent永久生效、--reload重载、--list-all查看规则。iptables(底层)：-A追加、-I插入、-D删除、-j ACCEPT/DROP动作。注意：firewalld和iptables不要混用；开放端口后记得--permanent+--reload；云服务器还需在控制台安全组放行。',
  'selinux': 'Security-Enhanced Linux，强制访问控制安全模块。getenforce查看状态(Enforcing/Permissive/Disabled)、setenforce 0临时设为宽容模式、chcon改安全上下文、semanage持久规则。比传统权限更细粒度，但配置复杂常导致权限拒绝。注意：排查权限问题可先setenforce 0确认是否SELinux导致；不建议直接Disabled，Permissive模式可审计但不阻断。',
  'useradd / passwd': '用户管理。useradd -m创建家目录、-g指定主组、-G附加组、-s指定shell。passwd设置/改密码。usermod修改、userdel删除(-r删家目录)。/etc/passwd存用户信息、/etc/shadow存密码哈希、/etc/group存组。注意：创建用户后需手动设密码才能登录；SSH密钥认证需将公钥放入~/.ssh/authorized_keys并设权限。',
  'sudo': 'superuser do，以管理员权限执行命令。sudo cmd临时提权，sudo -u user以指定用户执行，sudo -i切换到root环境。配置在/etc/sudoers，用visudo编辑(语法检查)。可配置哪些用户/组能执行哪些命令，实现精细化权限委派。注意：sudo比直接root登录更安全(有审计日志)；NOPASSWD免密码但降低安全性；sudo !!以sudo重跑上一条命令。',
  'logrotate': '日志轮转工具，自动切割/压缩/清理日志。配置在/etc/logrotate.d/，参数：daily/weekly频率、rotate 30保留份数、compress压缩、missingok不存在不报错、notifempty空文件不轮转、postrotate轮转后动作(如重载服务)。防止日志撑满磁盘。注意：logrotate靠cron触发(每天一次)；-d调试模式不实际执行；nginx/apache默认已有配置。',
  'at / batch': '一次性定时任务。at 3am tomorrow指定时间执行，atq查看队列，atrm删除。batch在系统负载低时执行。与cron区别：at只执行一次，cron周期执行。适合：定时重启、延迟处理、一次性备份。注意：atd服务需运行；时间格式灵活(at now+30min)；执行结果默认发邮件，建议重定向。',
  'uname / hostnamectl': '系统信息查看。uname -a显示内核版本/主机名/架构，-r只看内核版本。hostnamectl set-hostname永久设置主机名(比hostname命令更好)。/etc/os-release查看发行版信息。注意：内核版本影响驱动兼容；hostname在集群/日志分析中很重要，hostnamectl会同时改/etc/hostname和transient名称。',
  'dmesg': '显示内核环缓冲(kernel ring buffer)日志，包含硬件检测、驱动加载、内核错误等启动信息。-T人类可读时间、--level=err只看错误、|grep -i error过滤错误。排查硬件故障、驱动问题、内核崩溃(OOPS/Panic)的第一步。注意：dmesg时间戳默认是开机后秒数，-T转为可读时间；新内核日志也可通过journalctl -k查看。',
  'modprobe / lsmod': '内核模块管理。lsmod列出已加载模块，modprobe加载模块(自动处理依赖)、-r卸载、-c显示配置。modinfo查看模块信息。常见模块：br_netfilter(桥接网络过滤)、nfs(NFS文件系统)、vfio(VFIO设备直通)。注意：modprobe比insmod更智能(自动加载依赖)；/etc/modules-load/配置开机自动加载；模块加载失败检查dmesg。',
  'fdisk / parted': '磁盘分区工具。fdisk交互式(传统MBR，最大2TB)，parted支持GPT(大磁盘)。fdisk -l列出所有磁盘分区。分区步骤：选择磁盘→n新建→选类型→设大小→w写入。注意：分区后需mkfs格式化才能使用；GPT分区表支持更多分区且无2TB限制；操作前务必确认磁盘路径，误操作丢数据；云盘通常用 parted 或直接在控制台扩容。',
  'mkfs / mount': '格式化+挂载。mkfs.xfs/mkfs.ext4格式化分区(注意：会清空数据！)。mount挂载：mount /dev/sdb1 /data，-t指定类型、-o remount重挂载。卸载umount。开机自动挂载写入/etc/fstab(用UUID更可靠，blkid查UUID)。注意：挂载点目录需先创建；fstab配置错误会导致开机失败，建议mount -a测试后再重启。',
  'xfs_growfs / resize2fs': '在线扩容文件系统。云盘在控制台扩容后，需先growpart扩大分区，再xfs_growfs(XFS)或resize2fs(ext4)扩容文件系统。xfs_growfs /data扩大挂载在/data的XFS。注意：XFS只能扩大不能缩小；ext4可缩但需卸载；操作前先df -h确认当前大小，操作后df -h确认扩容成功；这是云运维常见操作。',
  'lsblk': 'list block devices，树状显示块设备(磁盘/分区)及挂载信息。-f显示文件系统类型/UUID、-o自定义输出列。比fdisk -l更直观，不需root。常用于：确认磁盘路径、查看分区结构、检查挂载状态。注意：lsblk显示的是内核视图，可能和实际挂载有短暂延迟；配合blkid查UUID、df查使用率使用。',
  'smartctl': 'SMART磁盘健康监控(smartmontools包)。-a显示所有信息、-H健康状态、-t long深度测试。关注：Reallocated_Sector_Ct(重映射扇区)、Current_Pending_Sector(待处理扇区)、Offline_Uncorrectable(不可纠正错误)。这些值非0说明磁盘有坏道。注意：SMART需BIOS开启；NVMe SSD用smartctl -a /dev/nvme0n1；定期检查提前预警磁盘故障。',
  'dd': '低级磁盘读写/复制工具。if输入、of输出、bs块大小(默认512B，设4M更快)、count数量。用途：制作启动盘(dd if=ubuntu.iso of=/dev/sdb bs=4M)、磁盘备份(dd if=/dev/sda of=img)、生成空文件(dd if=/dev/zero of=file bs=1M count=100)。注意：dd极其危险，of写错磁盘会瞬间清空数据！务必仔细确认路径；用status=progress显示进度。',
  'ansible': '批量自动化运维工具(SSH协议)。inventory定义主机，playbook(YAML)定义任务，module执行操作(shell/copy/yum/service)。幂等性：重复执行结果一致。ansible webservers -m ping测试连通性。无需agent，只需SSH。注意：~/.ansible.cfg或ansible.cfg配置；先ansible-galaxy安装role；生产环境用--check预演；变量用{{ var }}引用。',
  'terraform': '基础设施即代码(IaC)工具。.tf文件声明式定义云资源，terraform init初始化→plan预览变更→apply执行→destroy销毁。state文件记录当前状态(存远程backend如S3/OSS更安全)。支持AWS/阿里云/华为云等。注意：state文件是核心，务必妥善保管(远程+加密)；plan确认后再apply；destroy会删除所有资源，极度危险；用module组织复用。',
  'kubectl': 'Kubernetes命令行管理。get查看资源(pods/deployments/services)、describe详情(排查事件)、logs日志、exec进入容器、apply部署YAML、port-forward端口转发。-A所有命名空间、-o yaml详细格式。排查Pod问题：get pod→describe pod→logs。注意：配置在~/.kube/config；kubectl自动补全极大提升效率(source <(kubectl completion bash))；用alias k=kubectl省输入。',
  'helm': 'Kubernetes包管理器(类似apt/yum)。Chart是打包好的K8s应用模板。helm install部署、upgrade更新、rollback回滚、list查看、repo add添加仓库。values.yaml自定义配置覆盖默认值。比裸YAML更易管理复杂应用。注意：helm v3无需tiller更简单；生产环境用helmfile或ArgoCD管理多Chart；upgrade前先dry-run；values文件含敏感信息时勿提交。',
  'curl 健康检查': '用curl做服务健康检查。-s静默、-f HTTP错误返回非0、-o /dev/null丢弃body、-w \"%{http_code}\"只取状态码。脚本中：curl -sf http://localhost:8080/health || exit 1。配合--max-time 5防卡死、--retry 3自动重试。注意：健康检查端点应轻量(不查DB)；K8s liveness/readiness probe本质就是curl；监控脚本中常用。',
  'wget 镜像': '下载整站镜像。wget -m -k -K -E URL：-m镜像(递归+时间戳)、-k转绝对链接为相对、-K备份原文件、-E加.html扩展名。还可--convert-links转换链接、--page-requisites下载CSS/JS。注意：会创建大量文件，注意磁盘空间；robots.txt默认遵守，-e robots=off忽略；大量请求可能被服务器封IP，加--wait 1限速。',
  'supervisorctl': 'Supervisor进程管理工具(Python实现)。status/restart/start/stop控制进程，reread/reload重载配置。配置在/etc/supervisord.conf，定义program段。比nohup/screen更规范：自动重启、日志管理、集中控制。注意：supervisord本身需开机自启(systemctl enable supervisord)；适合管理非systemd服务(如旧版Node/Python进程)；优先用systemd管理。',
  'pip / conda': 'Python包管理。pip install安装、uninstall卸载、freeze导出依赖、-r从文件批量安装、--upgrade升级。conda管理Python环境+包，create -n env创建环境、activate激活。pip用requirements.txt，conda用environment.yml。注意：pip3指向Python3；虚拟环境(venv/conda env)隔离项目依赖避免冲突；国内用-i https://pypi.tuna.tsinghua.edu.cn/simple加速。',
  'nvm / npx': 'Node版本管理/包执行。nvm install 20安装、use 20切换、ls列出已装、alias default 20设默认。npx直接执行包(不需全局安装)，如npx create-vite myapp。注意：nvm切换Node版本后全局包需重装；.nvmrc文件固定项目Node版本；npx还可运行一次性命令(npx prettier --write .)；CI中用nvm use固定版本确保一致。',
  'jq': '命令行JSON处理工具。.取根、.key取字段、.arr[]遍历数组、.arr[].name取嵌套、|管道、select()过滤、map()映射、length长度。如：cat data.json|jq \'.users[]|{name,age}\'提取指定字段。API响应处理、配置文件查看、日志分析的利器。注意：jq默认美化输出，-c紧凑模式；配合curl处理API：curl api|jq；不支持YAML(用yq)。',
  'tree': '树状显示目录结构。-L 2限制深度、-d只看目录、-a显示隐藏文件、-I排除模式、--dirsfirst目录优先。常用于：项目结构文档、快速了解代码组织。注意：node_modules等大目录用-I排除；可输出到Markdown(tree -L 2 -I node_modules > STRUCTURE.md)；某些系统需自行安装。',
  'stat': '显示文件详细属性。Size大小、Blocks块数、IO Block I/O块大小、Mode权限、Uid/Gid所有者、Access/Modify/Change三个时间、Inode。比ls -l更详细。-c自定义格式：stat -c \'%s %a %U %n\' file输出大小/权限/所有者/文件名。注意：Access是最后访问时间、Modify是内容修改、Change是属性修改(如chmod)，三者不同。',
  'watch': '周期性执行命令并全屏显示结果。-n 2每2秒、-d高亮变化部分、-t不显示标题。如：watch -n 1 \'df -h\'每秒看磁盘、watch -d nvidia-smi高亮GPU变化。Ctrl+C退出。适合实时监控命令输出变化。注意：命令需用引号包裹(含管道/空格)；-n最小0.1秒；终端关闭则watch停止；复杂监控建议用tmux+watch组合。',
  'alias': '命令别名，简化常用命令。alias ll=\'ls -lah\'定义，unalias取消。当前shell有效，永久生效写入~/.bashrc。alias直接查看所有别名。注意：别名在脚本中默认不展开(需shopt -s expand_aliases)；别名不能含参数，需参数用function；alias git=hub类替换工具；过多别名可能让自己忘记原命令，建议适度使用。',
  'history': '命令历史记录。history|tail -20最近20条、!1234执行第1234条、!!上一条、!$上一条最后参数、Ctrl+R反向搜索。历史存~/.bash_history，HISTSIZE控制条数。注意：history -c清空当前会话历史；多终端并发写history可能丢失；敏感命令(含密码)建议先set +o history临时禁记录；HISTTIMEFORMAT加时间戳。',
  'tee': '从stdin读取同时输出到stdout和文件。make 2>&1|tee build.log：编译输出既显示又存日志。-a追加模式。常用于管道中保存中间结果、同时查看和记录输出。注意：tee默认覆盖文件，-a追加；sudo cmd|sudo tee file解决权限问题(管道后端tee也需sudo)；可写多个文件tee a.log b.log。',
  'xargs': '将stdin转为命令参数。find .-name \"*.log\"|xargs rm：把find结果作为rm参数删除。-I{}自定义占位符、-P4并行4个、-n1每次1个参数。解决\"命令参数太长\"问题和批量操作。注意：文件名含空格/特殊字符需find -print0|xargs -0；默认会执行echo；-P并行加速但注意顺序不保证；安全起见先预览(用echo替代实际命令)。',
  'date / timedatectl': '系统时间管理。date \"+%Y-%m-%d %H:%M:%S\"格式化输出、date -d \"2 days ago\"计算相对时间、date -s设置时间(需root)。timedatectl更现代：set-timezone Asia/Shanghai设时区、list-timezones列出时区、status查看状态。注意：timedatectl自动同步chrony/ntp；容器中时区默认UTC，需挂载/etc/localtime或设TZ环境变量；脚本中用$(date +%Y%m%d)生成日期戳。',
  'locale': '语言/编码设置。locale -a列出可用、locale-gen zh_CN.UTF-8生成、export LANG=zh_CN.UTF-8设置。影响日期格式、排序规则、字符分类等。中文乱码多因locale未设UTF-8。注意：需先locale-gen生成再设置；SSH客户端也需UTF-8编码；/etc/locale.conf全局设置；Docker中需在Dockerfile中设置ENV LANG。',
  'openssl': 'SSL/TLS工具包，证书生成/验签/加密。req生成证书请求、x509自签证书、genrsa生成RSA密钥、s_client测试SSL连接、enc对称加密。如：openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes生成自签证书。注意：自签证书浏览器不信任(仅测试用)；生产用Let\'s Encrypt或购买证书；私钥务必保密(权限600)。',
  'certbot': "Let's Encrypt免费SSL证书自动申请/续期。certbot --nginx -d example.com自动配置Nginx、--apache、--standalone独立模式。renew续期、renew --dry-run测试续期。证书90天有效，cron自动续期。注意：需80端口可访问验证域名所有权；--nginx自动改Nginx配置并重载；续期失败会邮件通知；通配符证书需DNS验证(--dns-cloudflare)。",
  'mysql / psql': '数据库CLI客户端。mysql -u root -p -e \"SQL\"执行SQL、-D选库、< file.sql执行脚本。psql -U user -d db -c \"SQL\"、\\l列库、\\dt列表、\\d表结构。注意：-p密码会暴露在进程列表/历史，用~/.my.cnf或PGPASSWORD环境变量更安全；生产环境避免直接CLI操作，用GUI工具或迁移工具；复杂查询用\\e调外部编辑器。',
  'redis-cli': 'Redis命令行客户端。-h host -p port -a password连接、INFO服务器信息、KEYS pattern键查找、FLUSHALL清空(危险！)、MONITOR实时命令监控。交互模式支持所有Redis命令。注意：KEYS *在大库上会阻塞(用SCAN替代)；-a密码不安全(用AUTH命令)；生产环境加--no-raw查看格式化输出；管道模式支持批量执行(python脚本生成命令|redis-cli --pipe)。',
  'mongosh': 'MongoDB Shell(mongo旧版已废弃)。连接：mongosh \"mongodb://user:pass@host:27017/db\"。常用：show dbs/collections、db.col.find()、insertOne/updateOne/deleteMany、aggregate聚合管道。--eval执行脚本。注意：MongoDB默认无认证(生产必须开启auth)；连接字符串中密码需URL编码；聚合管道功能强大但语法复杂，建议用GUI(Compass)辅助。',
  'nginx -t': 'Nginx配置检查/重载。-t检查语法(不重启)、-s reload优雅重载(不停服务)、-s stop停止、-T打印完整配置(含include)。修改配置后必须-t检查再reload。注意：-t检查语法不检查逻辑(如upstream不存在不会报错)；reload零停机重载配置；-T|grep server_name快速查看所有域名；日志在/var/log/nginx/，access.log和error.log。',
  'ab / wrk': 'HTTP压测工具。ab(Apache Bench)简单：-n请求数-c并发数。wrk更强大：-t线程-c并发-d持续时间、-H加请求头、-s Lua脚本(POST请求等)。如：wrk -t4 -c100 -d30s https://localhost/。注意：压测前先确认服务器能承受(别压垮生产)；ab不支持HTTPS需加-S；wrk的Lua脚本可模拟复杂场景；关注QPS/延迟/错误率；分布式压测用wrk2或Locust。',
  'du -sh': 'disk usage查看目录/文件磁盘占用。-s只显示总计不展开子目录、-h人类可读、--max-depth=1只看一层。du -sh /*|sort -rh|head -10找最大目录。注意：du会实际遍历文件计算大小(大目录慢)；--exclude排除目录；与df的区别：du是目录级别实际占用，df是文件系统级别；找大文件常配合find -size +100M。',
  'ncdu': 'NCurses Disk Usage，交互式磁盘分析工具。ncdu /扫描根目录，界面可上下浏览、d删除文件、q退出。比du更直观，快速定位大文件/大目录。注意：扫描大目录较慢(结果可导出ncdu -o file)；删除文件不可恢复(谨慎)；-x不跨文件系统；远程服务器磁盘满时ncdu -x /var快速定位日志文件。',
  'pidstat': '按进程查看资源使用(sysstat包)。-u CPU、-r内存、-d I/O、-w上下文切换，后接间隔秒数。如：pidstat -u 2每2秒显示各进程CPU。比top更适合记录/分析特定进程资源趋势。注意：-p PID只看指定进程；输出可存文件供分析；需root看所有进程；结合sar做历史趋势分析；I/O版本需内核开启taskstats。',
  'nvidia-smi': 'NVIDIA GPU监控。显示GPU利用率、显存使用、温度、功耗、进程。-l 2每2秒刷新、--query-gpu=utilization.gpu,memory.used --format=csv脚本友好输出。AI训练/推理服务器必备。注意：CUDA版本需与驱动匹配(nvidia-smi右上角显示)；显存碎片化可用nvidia-smi --gpu-reset清理(需停止所有进程)；多GPU用CUDA_VISIBLE_DEVICES指定。',
  'docker logs': '查看容器日志。-f实时跟踪、--tail 100最后100行、--since 2h最近2小时、-t时间戳、--details额外信息。容器日志默认存json-file驱动(无限增长，建议配置log-opts限制大小)。注意：容器应用需输出到stdout/stderr才能被docker logs捕获；日志驱动可改为syslog/fluentd等；--since时间过滤排查问题很方便。',
  'docker stats': '实时查看容器资源占用(类似top for containers)。--no-stream只输出一次(脚本用)、--format自定义格式。显示CPU/MEM/NET I/O/BLOCK I/O。注意：CPU%可能超100%(多核)；MEM LIMIT是容器内存限制；--no-stream适合监控脚本；持续运行有轻微开销；资源限制在docker run时用--cpus/--memory设置。',
  'docker exec': '在运行中的容器中执行命令。-i交互式、-t分配终端、-it组合进入shell。docker exec -it container sh进入容器调试。也可执行单条命令：docker exec container cat /etc/hosts。注意：容器需在运行状态；进入后exit退出不影响容器；生产容器可能没有shell(用distroless)，此时只能用nsenter或docker debug；优先用exec而非attach(attach会随退出而停止)。',
  'docker compose': '多容器编排工具(原docker-compose)。up -d启动、down停止删除、logs -f查看日志、ps状态、build构建、restart重启。docker-compose.yml定义服务/网络/卷。v2用docker compose(空格)非docker-compose(连字符)。注意：down -v删除卷(数据丢失！)；override文件分层覆盖(dev/prod不同配置)；生产环境复杂编排建议用K8s或Swarm。',
  'crictl': 'CRI(containerd/CRI-O)命令行工具，K8s节点调试用。ps容器列表、logs日志、exec进入、inspect详情、stats资源。当kubectl无法连接API Server时，在节点上用crictl直接排查。注意：需配置/etc/crictl.yaml指向runtime endpoint；K8s 1.24+移除dockershim后crictl更常用；与docker命令类似但操作的是K8s管理的容器。',
  'etcdctl': 'etcd键值存储CLI(K8s底层数据库)。get/set/del操作KV、--prefix范围查询、endpoint health健康检查、snapshot save备份。K8s所有状态(Pod/Service/Secret)存etcd。注意：K8s的etcd通常监听localhost:2379且需证书(--cacert等)；直接改etcd数据极度危险(可能损坏集群)；备份etcd是K8s灾备核心(etcdctl snapshot save)；v3 API用ETCDCTL_API=3。',
  'cloud-init': '云服务器首次启动初始化工具。配置在/etc/cloud/cloud.cfg和/var/lib/cloud/。status查看状态、query查元数据。处理：设置主机名、SSH密钥、磁盘挂载、包安装、用户脚本。注意：修改cloud-init配置后cloud-init clean重置；日志在/var/log/cloud-init.log；自定义脚本放/var/lib/cloud/scripts/per-instance/；排查云服务器启动问题第一步。',
  'aliyun cli': '阿里云命令行工具。configure配置AK/SK，各产品子命令：ecs云服务器、oss对象存储、rds数据库、vpc网络。如：aliyun ecs DescribeInstances查实例列表。支持JSON输出(--output cols=...)。注意：AK/SK配置在~/.aliyun/config.json(权限600)；RAM角色可免AK(实例元服务)；复杂操作用ROS(资源编排)或Terraform更合适；国内Region需--region cn-hangzhou。',
  'ossutil': '阿里云OSS对象存储工具。cp上传下载、sync同步、ls列举、rm删除、mb创建Bucket。-r递归、--exclude过滤。比aliyun cli oss更高效(大文件分片/断点)。注意：配置ossutil config(Endpoint/AK/SK)；大文件自动分片上传；sync --delete会删目标多余文件(谨慎)；国内访问用内网Endpoint省流量费；权限用ram-policy或Bucket Policy。',
  'huawei cli': '华为云CLI(hcloud)。configure配置认证，ECS/OBS/RDS等云服务操作。如：hcloud ECS ListServers查实例。支持--cli-region指定区域。注意：配置在~/.hcloud/；IAM token认证或AK/SK；OBS兼容S3协议可用aws s3 cli或s3cmd替代；华为云还提供SDK(Python/Java)适合复杂场景；Region如cn-north-4(北京4)。',
  'aws cli': 'AWS命令行工具。configure配置(AK/SK/Region)，s3/ec2/rds/iam等服务。s3 ls/cp/sync对象存储、ec2 describe-instances云服务器。--query JMESPath过滤输出、--output json/table/text。注意：配置在~/.aws/credentials和~/.aws/config；MFA需--serial-number；assume-role切换角色；Profile多账户(--profile prod)；S3兼容协议可操作阿里云OSS/MinIO。',
  'scp 云传输': '云服务器文件传输(基于SSH)。scp -i key.pem file root@host:/path上传、-r递归目录、-P端口。云服务器间传大文件建议内网IP(免流量费)。注意：scp每次全量传输，频繁同步用rsync；Windows下用WinSCP图形工具；端口与SSH一致(安全组需放行)；传压缩包(tar.gz)比传散文件快得多。',
  'rsync 云同步': '增量文件同步(基于SSH)。-a归档(保留权限/时间/软链)、-v详细、-z压缩传输、--delete保持一致、--exclude排除、--progress进度、--partial断点续传。rsync只传差异块，极适合大文件/频繁部署。注意：--delete会删目标多余文件(部署时有用但危险)；--dry-run预演；-e \"ssh -p 2222\"指定SSH端口；排除node_modules/.git等大目录。',
  'ssh 隧道': 'SSH端口转发/隧道。-L本地转发(访问本地端口=访问远程端口)：ssh -L 3306:localhost:3306 root@host，然后本地连localhost:3306即连远程MySQL。-R远程转发、-D动态SOCKS代理(-D 1080)。-N不执行命令(仅转发)、-f后台。注意：转发IP默认localhost(仅本机)，GatewayPorts=yes可外部访问；DB云内网时用-L安全访问；断线重连用autossh。',
  'fail2ban': 'SSH暴力破解防护。监控日志，对多次失败登录的IP自动封禁(调iptables/firewalld)。status查看状态、set unbanip解封。配置在/etc/fail2ban/jail.local。注意：默认保护SSH，可加jail保护Nginx/Apache；findtime时间窗口、maxretry最大重试、bantime封禁时长；自己被封需控制台解绑或等待过期；调整阈值避免误封正常用户。',
  'logrotate 云日志': '云服务器日志轮转。配置在/etc/logrotate.d/，每个服务一个文件。参数：daily/weekly按天/周、rotate 30保留30份、compress压缩旧日志、dateext用日期命名、sharedscripts多日志触发一次重载、postrotate/endscript轮转后执行(如通知服务重开日志文件)。注意：logrotate靠cron每天触发；nginx需postrotate发USR1信号重开日志；配置后logrotate -d验证(调试不执行)。',
  'ampl / cloudwatch': '云监控指标查看。AWS CloudWatch：get-metric-statistics查指标、--namespace AWS/EC2 --metric-name CPUUtilization。阿里云CloudMonitor类似。注意：CLI查指标较繁琐，控制台图表更直观；监控数据有延迟(1-5分钟)；自定义指标用put-metric-data上报；告警配置在控制台或IaC(Terraform)；费用：自定义指标和API调用可能收费。',
  'systemd-analyze': '系统启动性能分析。blame显示各服务启动耗时(从长到短)、critical-chain关键路径、time总启动时间、plot生成SVG时序图。排查开机慢的问题。注意：blame中耗时长的未必是瓶颈(可能并行启动)；critical-chain显示串行依赖链才是关键；优化：禁用不必要的服务(systemctl disable)、延迟非关键服务；plot输出SVG用浏览器打开更直观。',
  'nslookup / dig': 'DNS查询工具。dig +short example.com A查A记录(简洁)、@8.8.8.8指定DNS服务器、example.com MX查邮件记录、-x反查PTR。nslookup交互式(逐步淘汰，推荐dig)。排查：域名解析是否正确、DNS缓存、解析延迟、CDN节点。注意：dig返回含DNS查询耗时；+trace显示完整解析链路；本地DNS缓存 systemd-resolve --flush-caches 或 nscd；不同DNS结果可能不同(智能解析)。',
  'traceroute / mtr': '网络路由追踪。traceroute显示到目标的每一跳路由器及延迟，-T用TCP(防火墙可能挡ICMP)。mtr结合traceroute+ping持续刷新，--report模式输出固定报告。排查：网络延迟高/不通/丢包，定位是哪一跳的问题。注意：中间跳*可能是防火墙限速ICMP；mtr比traceroute更适合持续排查(看丢包率)；-T -p 443模拟HTTPS路径；网络问题先ping再mtr。',
}

let content = readFileSync('src/data/skills-data.js', 'utf8')

let count = 0
for (const [cmd, detail] of Object.entries(DETAILS)) {
  const escaped = cmd.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const regex = new RegExp(`(cmd: '${escaped}',\\s*desc: '[^']*?',\\s*example: '[^]*?',\\s*tags: \\[[^\\]]*?\\],\\s*freq: '[^']*?')`, 'g')
  const newContent = content.replace(regex, `$1, detail: '${detail.replace(/'/g, "\\'")}'`)
  if (newContent !== content) {
    count++
    content = newContent
  } else {
    console.log(`未匹配: ${cmd}`)
  }
}

writeFileSync('src/data/skills-data.js', content)
console.log(`已添加 detail 字段: ${count} 个命令`)